# Generated by Django 3.2.9 on 2021-12-06 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=250, unique=True, verbose_name='city')),
                ('country', models.CharField(max_length=250, verbose_name='country')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('longitude', models.FloatField(verbose_name='longitude')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'unique_together': {('latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='Datetimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(unique=True, verbose_name='dates')),
            ],
            options={
                'verbose_name': 'Дату',
                'verbose_name_plural': 'Даты',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('message', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'email',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='Weather_measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.IntegerField(null=True, verbose_name='humidity')),
                ('pressure', models.IntegerField(null=True, verbose_name='pressure')),
                ('temperature', models.FloatField(null=True, verbose_name='temperature')),
                ('wind_direction', models.IntegerField(null=True, verbose_name='wind_direction')),
                ('wind_speed', models.IntegerField(null=True, verbose_name='wind_speed')),
                ('description', models.CharField(max_length=250, null=True, verbose_name='description')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cities')),
                ('datetime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.datetimes')),
            ],
            options={
                'verbose_name': 'Описание погоды',
                'verbose_name_plural': 'описания погоды',
                'unique_together': {('datetime', 'city')},
            },
        ),
    ]
